name: Release
on:
  push:
    tags: ['v*']
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: emover-linux-x64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: emover-linux-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: emover-macos-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: emover-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: emover-windows-x64.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo build --release --target ${{ matrix.target }} --manifest-path emover/Cargo.toml
      - run: cp emover/target/${{ matrix.target }}/release/emover* ${{ matrix.name }}
        shell: bash
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.name }}

